src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Catname = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Product::class)]
    private Collection $Products;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo = null;

    public function __construct()
    {
        $this->Products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCatname(): ?string
    {
        return $this->Catname;
    }

    public function setCatname(?string $Catname): static
    {
        $this->Catname = $Catname;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->Products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->Products->contains($product)) {
            $this->Products->add($product);
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->Products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Container61FWced\getCategoryRepositoryService;
use App\Entity\Product;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;


class CategoryType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('CatName', TextType::class)
                ->add('logoImage', FileType::class, [
                    'label' => 'Image file',
                    'mapped' => false,
                    'required' => false,
                    'constraints' => [
                        new File([
                            'maxSize' => '1024k',
                            'mimeTypesMessage' => 'Please upload a valid image',
                        ])
                    ],
                ])
            ;
    }

    public function getBlockPrefix()
    {
        return 'cha_stripe_payment_form';
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Product;
use App\Form\CategoryType;
use App\Form\ProductType;
use App\Manager\CartManager;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use App\Repository\CategoryRepository;
class CategoryController extends AbstractController
{

    #[Route('/category/view/{id}', name: 'category_view')]
    public function viewCategory( $id, ManagerRegistry $doctrine, CartManager $cartManager): Response
    {
        $category_id = $doctrine->getManager();
        $categories = $category_id->getRepository(Category::class)->find($id);
        $products = $categories->getProducts();
        $cart = $cartManager->getCurrentCart();


        return $this->render('category/view.html.twig',['products' => $products,'categories'=>$categories, 'cart' => $cart]);
    }




    #[Route('/category/details', name: 'category_details')]
    public function detailsCategory(ManagerRegistry $doctrine, CartManager $cartManager): Response
    {
        $products = $doctrine->getRepository(Product::class)->findAll();
        $categories = $doctrine->getRepository(Category::class)->findAll();
        $cart = $cartManager->getCurrentCart();

        return $this->render('category/details.html.twig', [
            'products' => $products, 'categories'=>$categories, 'cart' => $cart
        ]);
    }

    #[Route('/admin/category/delete/{id}', name: 'category_delete')]
    public function deleteCategory(ManagerRegistry $doctrine,$id)
    {
        $em = $doctrine->getManager();
        $categories = $em->getRepository(Category::class)->find($id);
        $em->remove($categories);
        $em->flush();

        $this->addFlash(
            'error',
            'Category deleted'
        );
        return $this->redirectToRoute('product_list');
    }




//    #[Route('/admin/category/create', name: 'category_create')]
//    public function createCategory(ManagerRegistry $doctrine,Request $request)
//    {
//
//        $products = $doctrine->getRepository(Category::class)->findAll();
//        $categories = new Category();
//        $form = $this->createForm(CategoryType::class, $categories);
//
//        $form->handleRequest($request);
//        if ($form->isSubmitted() && $form->isValid()) {
//            $em = $doctrine->getManager();
//            $em->persist($categories);
//            $em->flush();
//
//            $this->addFlash(
//                'notice',
//                'Category Added'
//            );
//
//            return $this->redirectToRoute('category_details', [
//                'id' => $categories->getId()
//            ]);
//
//        }
//
//        return $this->renderForm('category/create.html.twig', ['form' => $form, 'categories'=>$categories, '$products'=>$products]);
//    }

    #[Route('/admin/category/create', name: 'category_create')]
    public function createCategory(ManagerRegistry $doctrine, Request $request, SluggerInterface $slugger, CartManager $cartManager)
    {
        $products = $doctrine->getRepository(Category::class)->findAll();
        $categories = new Category();
        $form = $this->createForm(CategoryType::class, $categories);
        $cart = $cartManager->getCurrentCart();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Các đoạn code khác

            // upload file
            $logoImage = $form->get('logoImage')->getData();
            if ($logoImage) {
                $originalFilename = pathinfo($logoImage->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $logoImage->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $logoImage->move(
                        $this->getParameter('logoImage_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash(
                        'error',
                        'Cannot upload'
                    );// ... handle exception if something happens during file upload
                }
                $categories->setLogo($newFilename);
            } else {
                $this->addFlash(
                    'error',
                    'Cannot upload'
                );// ... handle exception if something happens during file upload
            }

            $em = $doctrine->getManager();
            $em->persist($categories);
            $em->flush();

            $this->addFlash(
                'notice',
                'Product Added'
            );
            return $this->redirectToRoute('category_details', [
                'id' => $categories->getId()
            ]);
        }

        return $this->renderForm('category/create.html.twig', ['form' => $form, 'categories' => $categories, 'products' => $products, 'cart' => $cart]);
    }

//    #[Route('/category/edit/{id}', name: 'category_edit')]
//    public function editAction(ManagerRegistry $doctrine, int $id,Request $request): Response{
//        $entityManager = $doctrine->getManager();
//        $categories = $entityManager->getRepository(Category::class)->find($id);
//        $form = $this->createForm(CategoryType::class, @$categories);
//        $form->handleRequest($request);
//        $products = $doctrine->getRepository(Category::class)->findAll();
//        if ($form->isSubmitted() && $form->isValid()) {
//
//            $em = $doctrine->getManager();
//            $em->persist($categories);
//            $em->flush();
//            return $this->redirectToRoute('category_details', [
//                'id' => $categories->getId()
//            ]);
//
//        }
//        return $this->renderForm('category/edit.html.twig', ['form' => $form,'categories'=>$categories, '$products'=>$products]);
//    }

    #[Route('/category/edit/{id}', name: 'category_edit')]
    public function editAction(ManagerRegistry $doctrine, int $id, Request $request, SluggerInterface $slugger, CartManager $cartManager): Response
    {
        $entityManager = $doctrine->getManager();
        $categories = $entityManager->getRepository(Category::class)->find($id);
        $form = $this->createForm(CategoryType::class, $categories);
        $form->handleRequest($request);
        $products = $doctrine->getRepository(Category::class)->findAll();
        $cart = $cartManager->getCurrentCart();

        if ($form->isSubmitted() && $form->isValid()) {

            // upload file
            $logoImage = $form->get('logoImage')->getData();
            if ($logoImage) {
                $originalFilename = pathinfo($logoImage->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $logoImage->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $logoImage->move(
                        $this->getParameter('logoImage_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash(
                        'error',
                        'Cannot upload'
                    );// ... handle exception if something happens during file upload
                }
                $categories->setLogo($newFilename);
            } else {
                $this->addFlash(
                    'error',
                    'Cannot upload'
                );// ... handle exception if something happens during file upload
            }

            $em = $doctrine->getManager();
            $em->persist($categories);
            $em->flush();

            return $this->redirectToRoute('category_details', [
                'id' => $categories->getId()
            ]);
        }

        return $this->renderForm('category/edit.html.twig', ['form' => $form, 'categories' => $categories, 'products' => $products, 'cart' => $cart]);
    }
}

templates/category/create.html.twig
{% extends 'base.html.twig' %}
{#{% extends 'base.html.twig' %}#}
{% block body %}
    <div class="container mt-5">

        <ul class="list-group">
            <li class="list-group-item" style="background-color: #505050"><h2 style="color: white; text-align: center">Create Category</h2></li>
            <li class="list-group-item">
                {{ form_start(form) }}
                <div class="form-group">
                    <label for="CatName"><strong>Name:</strong></label>
                    {{ form_widget(form.CatName,{
                        'attr':{
                            'class':'form-control'
                        }
                    }) }}
                    <div class="form-group">
                        <label for="due_date">Choose an Image</label>
                        {{ form_widget(form.logoImage,{
                        }) }}
                    </div><br>
                <input type="submit" name="create_category" value="Success" class="btn btn-success btn btn-primary" style="float: right"/>
                {{ form_end(form) }}
            </li>

        </ul></div> <br><br><br><br><br><br><br><br><br>

{% endblock %}

templates/category/details.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<br><br>
    <div class="container-fluid mt-3">
        <div class="row">
        <div class="col-sm-3"><ul class="list-group">
                <li class="list-group-item">
    <div class="bs-example" data-example-id="striped-table">
        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Collection 84RISING*</th>

            </tr>
            </thead>
            <tbody><ul class="nav">

            {% for category in categories %}
                <tr>
                    <th scope="row">{{ category.id }}</th>
                        <td><a href="{{path('productByCat',{'id':category.id})}} " class='nav-link button button5' style="border:2px solid Gray;text-align: center">{{ category.catname }}</a></td>
                    {% if is_granted('ROLE_ADMIN') %}
                        <td><a href="{{path('category_edit',{'id':category.id})}} " class='nav-link button button1' style="border:2px solid MediumSeaGreen;text-align: center">Edit</a></td>
                       <td><a href="{{ path('category_delete', {'id': category.id}) }} "class='nav-link button button3' style="border:2px solid Red;text-align: center">Delete</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </ul>
            </tbody>

        </table>
        <table class="table table-striped"><tbody><tr><td><a href="{{path('category_details')}}" class='nav-link button button4' style="text-align: center">All Category</a></td></tr></tbody></table>

        <!-- Carousel -->
        <div id="demo" class="carousel slide" data-bs-ride="carousel">

            <!-- Indicators/dots -->
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="3"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="4"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="5"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="6"></button>
            </div>

            <!-- Left and right controls/icons -->
            <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">

            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">

            </button>
        </div>

    </div></li>
            </ul></div>


            <div class="col-sm-9">
                <div class="container mt-3">
                    <div class="row">
                        {% for product in products %}
                        <div class="col-md-3">
                            <div class="card zoom-effect" style="width: 310px; border: none;">
                                <div class="card-body" style="height: 370px;">
                                    <a href="{{ path('product_details', {'id': product.id}) }}" style="text-decoration: none; color: inherit;">
                                        <img src="{{ asset('uploads/image/' ~ product.productImage) }}" class="card-img-top" height="200px" width="250px" alt="Product Image">
                                        <br><br>
                                        <h4 style="height: 70px; overflow: hidden; font-size: 18px;">{{ product.name }}</h4>
                                        <div class="row">
                                            <div class="col">
                                <span style="font-size: 20px">
                                    <strong style="color: red">{{ product.price }}$</strong>
                                </span>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div><br>
                        </div>
                        {% endfor %}
                    </div>
                    <br>
                </div>
            </div>
    </div></div>
<br><br><br><br>
    <style>
        .zoom-effect img {
            transition: transform 2s ease;
        }

        .zoom-effect:hover img {
            transform: scale(1.1);
        }
        .button {
             /* Green */
            border: none;

            transition-duration: 0.4s;
            cursor: pointer;
        }

        .button1 {

            color: black;
            border: 2px solid #28B463;
        }

        .button1:hover {
            background-color: #28B463;
            color: white;
        }

        .button2 {
            background-color: white;
            color: black;
            border: 2px solid #008CBA;
        }

        .button2:hover {
            background-color: #008CBA;
            color: white;
        }

        .button3 {

            color: black;
            border: 2px solid #CB4335;
        }

        .button3:hover {
            background-color: #CB4335;
            color: white;
        }

        .button4 {
            color: black;
            border: 0 solid #e7e7e7;
        }

        .button4:hover {background-color: #717D7E;
            color: white;}

        .button5 {

            color: black;
            border: 2px solid #555555;
        }

        .button5:hover {
            background-color: #555555;
            color: white;
        }

    </style>
{% endblock %}

templates/category/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container mt-5">

        <ul class="list-group">
            <li class="list-group-item" style="background-color: #505050"><h2 style="color: white; text-align: center">Edit Category</h2></li>
            <li class="list-group-item">
                {{ form_start(form) }}
                <div class="form-group">
                    <label for="CatName"><strong>Name:</strong></label>
                    {{ form_widget(form.CatName,{
                        'attr':{
                            'class':'form-control'

                        }
                    }) }}
                    <div class="form-group">
                        <label for="due_date">Choose an Image</label>
                        {{ form_widget(form.logoImage,{

                        }) }}
                    </div><br>
                    <input type="submit" name="edit_category" value="Success" class="btn btn-success btn btn-primary" style="float: right"/>
                    {{ form_end(form) }}
            </li>

        </ul></div> <br><br><br><br><br><br><br><br><br>

{% endblock %}

templates/category/view.html.twig
{% extends 'base.html.twig' %}
{% block body %}


    <div class="container">
        <h1 class="mt-5 mb-6" style="font-size: 60px; left: 60px">{{ categories.catname }}</h1>
        <div class="row">
            {% for product in products %}
                <div class="col-md-4" style="box-sizing: border-box; padding: 0; margin: 0;">
                    <div class="card mb-4" style="max-width: 400px;max-height: 320px; margin: 0 auto; padding: 0 0; width: 100%; height: 100%; position: relative;">
                        <a class="rounded" style="align-items: center" href="{{path('product_details',{'id':product.id})}}">
                            <img height="200px" src="{{ asset('uploads/image/' ~ product.productImage)}}" alt="{{ product.name }}" class="card-img-top"></a>
                        <div class="card-body"><abbr>
                            <p class="card-title" style="text-align: center">{{ product.name }}</p></abbr>
                             <style>p{font-size: 20px; font-weight: 600}</style>

                            <div class="d-flex justify-content-between align-item-center">

                                <span class="h5 mt-auto" style="font-size: 20px;margin-right: auto;margin-left: auto;margin-top: auto;margin-bottom: auto; font-weight: 500; color: red">{{ product.price }}$</span>

                            </div><br><br>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}